<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Форма</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h3>Создание заявки</h3>
    <form action="/sendForm.php" method="get">
        <div class="mb-3">
            <input type="text" class="form-control" placeholder="Имя" name="name">
        </div>
        <div class="mb-3">
            <input type="email" class="form-control" placeholder="Email" name="email">
        </div>
        <div class="mb-3">
            <input type="tel" class="form-control" placeholder="Телефон" name="tel">
        </div>
        <div class="mb-3">
            <input type="number" class="form-control" placeholder="Цена" name="price">
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>
</body>
</html>